# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.dbManager:
        class: AppBundle\Services\DatabaseManager
        arguments: ["@doctrine.orm.entity_manager"]

    app.twig.extension.time_diff:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: 'twig.extension' }

    app.twig.extension.greeting:
        class: AppBundle\Twig\Holidays
        public: true
        tags:
            - { name: twig.extension }

    app.article_voter:
            class: AppBundle\Security\ArticleVoter
            arguments: ['@security.access.decision_manager']
            tags:
                - {name: security.voter}
            public: false
